### PR TITLE
Tag colors 3

### PR DESCRIPTION
**Pull request by FerSabGar**
@conema. I've forked your #40 (Tag colors 2) and I made those needed changes to draw a gradient highlight for non-tagged messages in the message list acoording to differrent intensity of the same color (see #31 for more information).  Now it is also possible to personalize the gradient colors through the userChrome.css file.
If you agree we could merge both tag-colors-2 in a new one brack (tag-color-3).
This is my first pull request, so I'm not really knowing what I'm doing. So please, I give you the control of this.
Let me know what you think.

### CODE REVIEW

**Comment by FerSabGar** [comment]
Regarding the system theme I chose to maintain the highlight without gradient, but users can easily setup it with new options in userChrome.ccs.

I was no able to manage totally this theme because I don't know how to create another color (to draw the gradient)  based on the Highlight color. I'm sorry.

**Comment by conema** [comment]
@FerSabGar As I told you in the other message, I'm happy to see that you created this commit. I will merge this (or maybe you could make a PR directly into the spymastermatt's repostory) when @spymastermatt will accept the PR that are present.

**Comment by FerSabGar** [comment]
@conema Let me know what option you believe is more adequate. If it is convenient, I have no problem in proposing a PR to @spymastermatt after he have accepted the current one.

**Comment by conema** [comment]
@FerSabGar More than anything I wouldn't like to take credit for what you did!
I'll update you when spymastermatt will accept the PR.

**Comment by FerSabGar** [comment]
@conema I know that, I know. It was not my intention to suggest that point. In fact, credit is not really important, at least in this context. ;-))

**Comment by conema** [comment]
@FerSabGar  Mhmh, I think that we will wait for a while...

**Comment by spymastermatt** [comment]
@conema @FerSabGar Please see my comment on @conema 's PR
https://github.com/spymastermatt/thunderbird-monterail/pull/40#issuecomment-303491752

**Comment by conema** [comment]
Updated my fork.

**Pull request closed without merging**
